
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
{'name': 'egofm', 'stream': 'http://mp3ad.egofm.c.nmdn.net/ps-egofm_128/livestream.mp3', 'onlineradiobox': 'https://onlineradiobox.com/de/ego/playlist/?cs=de.ego', 'id': 'channel_id1'}
Writing JSON
Audio codec mp3float channels 2 samplerate 44100 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
[2020-03-23 11:46:16,227] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/share/radioflask/views.py", line 454, in home
    session.pop('current_channels')
  File "/home/pi/.local/lib/python3.7/site-packages/werkzeug/datastructures.py", line 269, in pop
    rv = super(UpdateDictMixin, self).pop(key)
KeyError: 'current_channels'
192.168.0.54 - - [23/Mar/2020 11:46:16] "GET / HTTP/1.1" 500 -
['Alice Phoebe Lou - Witches - 2020-03-23 11:46']
Writing JSON
